- name: Deploy static website on Apache
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Copy website files to Apache directory
      copy:
        src: ./oxer-linux-apache/
        dest: /var/www/html/
        owner: ec2-user
        group: ec2-user
        mode: '0755'
